"""add promo tracking columns

Revision ID: 04e031af9c3a
Revises: 009_stockout_transaction
Create Date: 2025-12-23 19:28:13.162215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '04e031af9c3a'
down_revision: Union[str, None] = '009_stockout_transaction'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_algorithm_runs_date'), table_name='algorithm_runs')
    op.drop_index(op.f('idx_algorithm_runs_restaurant'), table_name='algorithm_runs')
    op.drop_index(op.f('idx_health_scores_restaurant_date'), table_name='data_health_scores')
    op.alter_column('data_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_data_uploads_file_hash'), table_name='data_uploads')
    op.drop_index(op.f('ix_data_uploads_restaurant_id'), table_name='data_uploads')
    op.drop_constraint(op.f('data_uploads_restaurant_id_fkey'), 'data_uploads', type_='foreignkey')
    op.create_foreign_key(None, 'data_uploads', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_index(op.f('idx_forecasts_date'), table_name='demand_forecasts')
    op.drop_index(op.f('idx_forecasts_restaurant'), table_name='demand_forecasts')
    op.drop_index(op.f('idx_availability_employee'), table_name='employee_availability')
    op.drop_constraint(op.f('uq_employee_roles_restaurant_name'), 'employee_roles', type_='unique')
    op.drop_index(op.f('idx_employees_active'), table_name='employees')
    op.drop_index(op.f('idx_employees_restaurant'), table_name='employees')
    op.drop_index(op.f('idx_ingestion_logs_upload'), table_name='ingestion_logs')
    op.drop_constraint(op.f('uq_ingredient_categories_restaurant_name'), 'ingredient_categories', type_='unique')
    op.drop_index(op.f('idx_ingredients_restaurant'), table_name='ingredients')
    op.drop_index(op.f('idx_inventory_expiry'), table_name='inventory')
    op.drop_index(op.f('idx_inventory_ingredient'), table_name='inventory')
    op.drop_index(op.f('idx_inventory_restaurant'), table_name='inventory')
    op.drop_index(op.f('idx_inventory_movements_date'), table_name='inventory_movements')
    op.drop_index(op.f('idx_inventory_movements_restaurant'), table_name='inventory_movements')
    op.drop_index(op.f('idx_inventory_restaurant_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('idx_inventory_unique'), table_name='inventory_snapshots')
    op.drop_index(op.f('idx_events_date'), table_name='local_events')
    op.drop_index(op.f('idx_events_restaurant'), table_name='local_events')
    op.drop_constraint(op.f('uq_menu_categories_restaurant_name'), 'menu_categories', type_='unique')
    op.drop_index(op.f('idx_price_history_item_date'), table_name='menu_item_price_history')
    op.alter_column('menu_items', 'auto_created',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_menu_items_active'), table_name='menu_items')
    op.drop_index(op.f('idx_menu_items_auto_created'), table_name='menu_items')
    op.drop_index(op.f('idx_menu_items_confidence'), table_name='menu_items')
    op.drop_index(op.f('idx_menu_items_restaurant'), table_name='menu_items')
    op.drop_index(op.f('idx_promotions_dates'), table_name='promotions')
    op.drop_index(op.f('idx_promotions_restaurant'), table_name='promotions')
    op.drop_index(op.f('idx_recipes_ingredient'), table_name='recipes')
    op.drop_index(op.f('idx_recipes_menu_item'), table_name='recipes')
    op.drop_constraint(op.f('uq_recipes_item_ingredient'), 'recipes', type_='unique')
    op.drop_constraint(op.f('uq_settings_restaurant_key'), 'restaurant_settings', type_='unique')
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_restaurants_owner_id'), table_name='restaurants')
    op.drop_constraint(op.f('restaurants_owner_id_fkey'), 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'])
    op.alter_column('scheduled_shifts', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_scheduled_shifts_date'), table_name='scheduled_shifts')
    op.drop_index(op.f('idx_scheduled_shifts_employee'), table_name='scheduled_shifts')
    op.drop_index(op.f('idx_scheduled_shifts_restaurant'), table_name='scheduled_shifts')
    op.drop_constraint(op.f('uq_skills_restaurant_name'), 'skills', type_='unique')
    op.drop_index(op.f('idx_staffing_forecasts_date'), table_name='staffing_forecasts')
    op.alter_column('transaction_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_transaction_items_source_hash'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.add_column('transactions', sa.Column('is_promo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('transactions', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_restaurant_id'), table_name='transactions')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_weather_location_date'), 'weather_data', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_weather_location_date'), 'weather_data', ['location', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_transactions_restaurant_id'), 'transactions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['transaction_date'], unique=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('transactions', 'discount_amount')
    op.drop_column('transactions', 'is_promo')
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_transaction_items_source_hash'), 'transaction_items', ['source_hash'], unique=False)
    op.alter_column('transaction_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_staffing_forecasts_date'), 'staffing_forecasts', ['restaurant_id', 'forecast_date'], unique=False)
    op.create_unique_constraint(op.f('uq_skills_restaurant_name'), 'skills', ['restaurant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_scheduled_shifts_restaurant'), 'scheduled_shifts', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_scheduled_shifts_employee'), 'scheduled_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('idx_scheduled_shifts_date'), 'scheduled_shifts', ['shift_date'], unique=False)
    op.alter_column('scheduled_shifts', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key(op.f('restaurants_owner_id_fkey'), 'restaurants', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_restaurants_owner_id'), 'restaurants', ['owner_id'], unique=False)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_settings_restaurant_key'), 'restaurant_settings', ['restaurant_id', 'setting_key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_recipes_item_ingredient'), 'recipes', ['menu_item_id', 'ingredient_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_recipes_menu_item'), 'recipes', ['menu_item_id'], unique=False)
    op.create_index(op.f('idx_recipes_ingredient'), 'recipes', ['ingredient_id'], unique=False)
    op.create_index(op.f('idx_promotions_restaurant'), 'promotions', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_promotions_dates'), 'promotions', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('idx_menu_items_restaurant'), 'menu_items', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_menu_items_confidence'), 'menu_items', ['restaurant_id', 'confidence_score'], unique=False)
    op.create_index(op.f('idx_menu_items_auto_created'), 'menu_items', ['restaurant_id', 'auto_created'], unique=False)
    op.create_index(op.f('idx_menu_items_active'), 'menu_items', ['restaurant_id', 'is_active'], unique=False)
    op.alter_column('menu_items', 'auto_created',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_price_history_item_date'), 'menu_item_price_history', ['menu_item_id', 'effective_date'], unique=False)
    op.create_unique_constraint(op.f('uq_menu_categories_restaurant_name'), 'menu_categories', ['restaurant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_events_restaurant'), 'local_events', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_events_date'), 'local_events', ['event_date'], unique=False)
    op.create_index(op.f('idx_inventory_unique'), 'inventory_snapshots', ['restaurant_id', 'menu_item_id', 'date'], unique=True)
    op.create_index(op.f('idx_inventory_restaurant_date'), 'inventory_snapshots', ['restaurant_id', 'date'], unique=False)
    op.create_index(op.f('idx_inventory_movements_restaurant'), 'inventory_movements', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_inventory_movements_date'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('idx_inventory_restaurant'), 'inventory', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_inventory_ingredient'), 'inventory', ['ingredient_id'], unique=False)
    op.create_index(op.f('idx_inventory_expiry'), 'inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('idx_ingredients_restaurant'), 'ingredients', ['restaurant_id'], unique=False)
    op.create_unique_constraint(op.f('uq_ingredient_categories_restaurant_name'), 'ingredient_categories', ['restaurant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ingestion_logs_upload'), 'ingestion_logs', ['upload_id'], unique=False)
    op.create_index(op.f('idx_employees_restaurant'), 'employees', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_employees_active'), 'employees', ['restaurant_id', 'is_active'], unique=False)
    op.create_unique_constraint(op.f('uq_employee_roles_restaurant_name'), 'employee_roles', ['restaurant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_availability_employee'), 'employee_availability', ['employee_id'], unique=False)
    op.create_index(op.f('idx_forecasts_restaurant'), 'demand_forecasts', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_forecasts_date'), 'demand_forecasts', ['forecast_date'], unique=False)
    op.drop_constraint(None, 'data_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('data_uploads_restaurant_id_fkey'), 'data_uploads', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_data_uploads_restaurant_id'), 'data_uploads', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_data_uploads_file_hash'), 'data_uploads', ['restaurant_id', 'file_hash'], unique=False)
    op.alter_column('data_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_health_scores_restaurant_date'), 'data_health_scores', ['restaurant_id', 'calculated_at'], unique=False)
    op.create_index(op.f('idx_algorithm_runs_restaurant'), 'algorithm_runs', ['restaurant_id'], unique=False)
    op.create_index(op.f('idx_algorithm_runs_date'), 'algorithm_runs', ['run_started_at'], unique=False)
    # ### end Alembic commands ###
