"""add forecast tables

Revision ID: 214f256ebc5b
Revises: 2d402a57df19
Create Date: 2025-12-23 23:37:20.265220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214f256ebc5b'
down_revision: Union[str, None] = '2d402a57df19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_forecasts', sa.Column('menu_item_name', sa.String(), nullable=False))
    op.add_column('demand_forecasts', sa.Column('model_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('demand_forecasts_menu_item_id_fkey'), 'demand_forecasts', type_='foreignkey')
    op.drop_constraint(op.f('demand_forecasts_restaurant_id_fkey'), 'demand_forecasts', type_='foreignkey')
    op.create_foreign_key(None, 'demand_forecasts', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('demand_forecasts', 'menu_item_id')
    op.drop_column('demand_forecasts', 'upper_bound')
    op.drop_column('demand_forecasts', 'model_version')
    op.drop_column('demand_forecasts', 'lower_bound')
    op.drop_column('demand_forecasts', 'factors')
    op.add_column('staffing_forecasts', sa.Column('predicted_hours', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('staffing_forecasts', sa.Column('model_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('staffing_forecasts_restaurant_id_fkey'), 'staffing_forecasts', type_='foreignkey')
    op.drop_constraint(op.f('staffing_forecasts_role_id_fkey'), 'staffing_forecasts', type_='foreignkey')
    op.create_foreign_key(None, 'staffing_forecasts', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('staffing_forecasts', 'role_id')
    op.drop_column('staffing_forecasts', 'recommended_staff')
    op.drop_column('staffing_forecasts', 'predicted_covers')
    op.drop_column('staffing_forecasts', 'hour_of_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffing_forecasts', sa.Column('hour_of_day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('staffing_forecasts', sa.Column('predicted_covers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('staffing_forecasts', sa.Column('recommended_staff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('staffing_forecasts', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staffing_forecasts', type_='foreignkey')
    op.create_foreign_key(op.f('staffing_forecasts_role_id_fkey'), 'staffing_forecasts', 'employee_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('staffing_forecasts_restaurant_id_fkey'), 'staffing_forecasts', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('staffing_forecasts', 'model_name')
    op.drop_column('staffing_forecasts', 'predicted_hours')
    op.add_column('demand_forecasts', sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('demand_forecasts', sa.Column('lower_bound', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('demand_forecasts', sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('demand_forecasts', sa.Column('upper_bound', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('demand_forecasts', sa.Column('menu_item_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'demand_forecasts', type_='foreignkey')
    op.create_foreign_key(op.f('demand_forecasts_restaurant_id_fkey'), 'demand_forecasts', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('demand_forecasts_menu_item_id_fkey'), 'demand_forecasts', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('demand_forecasts', 'model_name')
    op.drop_column('demand_forecasts', 'menu_item_name')
    # ### end Alembic commands ###
