"""add operating hours columns

Revision ID: 2d402a57df19
Revises: 04e031af9c3a
Create Date: 2025-12-23 19:38:50.522246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d402a57df19'
down_revision: Union[str, None] = '04e031af9c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('first_order_time', sa.Time(), nullable=True))
    op.add_column('transactions', sa.Column('last_order_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'last_order_time')
    op.drop_column('transactions', 'first_order_time')
    # ### end Alembic commands ###
