"""add_probabilistic_forecast_columns

Revision ID: dc0aada3a1b6
Revises: 012_recipe_intel
Create Date: 2025-12-25 22:39:02.832269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0aada3a1b6'
down_revision: Union[str, None] = '012_recipe_intel'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_forecasts', sa.Column('p10_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('demand_forecasts', sa.Column('p50_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('demand_forecasts', sa.Column('p90_quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand_forecasts', 'p90_quantity')
    op.drop_column('demand_forecasts', 'p50_quantity')
    op.drop_column('demand_forecasts', 'p10_quantity')
    # ### end Alembic commands ###
